server:
  port: 8000
spring:
  application:
    name: user-service    # 项目名称尽量用小写
  datasource:
    name: test
    url: jdbc:mysql://135.192.86.200:3306/flow_app
    username: flow
    password: flow#1223
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
logging:
  file: ./logs/UserService.log
  level:
    root: INFO
    com.java110.user: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/  # 指定注册中心的地址, http://discovery:8762/eureka/
  instance:
    preferIpAddress: true
