version: '2'
services:
   userservice:
       container_name: userservice-1
       build:
          context: .
          dockerfile: Dockerfile
       restart: always
       ports:
       - "8002:8002"
       volumes:
       - ../target/UserService.jar:/root/target/UserService.jar
       network_mode: "host"
#       extra_hosts:
#       - "dev.java110.com:192.168.1.18"
#       - "dev.db.java110.com:192.168.1.18"
#       - "dev.zk.java110.com:192.168.1.18"
#       - "dev.kafka.java110.com:192.168.1.18"
#       - "dev.redis.java110.com:192.168.1.18"
#       - "api.java110.com:92.168.1.18"