version: '2'
services:
   api:
       container_name: api-1
       build:
          context: .
          dockerfile: Dockerfile
       restart: always
       ports:
       - "8008:8008"
       volumes:
       - ../target/Api.jar:/root/target/Api.jar
       networks:
       - java110-net
       mem_limit: 1024m
#       extra_hosts:
#       - "dev.java110.com:192.168.1.18"
#       - "dev.db.java110.com:192.168.1.18"
#       - "dev.zk.java110.com:192.168.1.18"
#       - "dev.kafka.java110.com:192.168.1.18"
#       - "dev.redis.java110.com:192.168.1.18"
#       - "api.java110.com:92.168.1.18"
networks:
  java110-net:
    external: true